Install Java using the setup-java action

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -24,7 +24,6 @@ runs:
         key: neo4j-${{ inputs.neo4j-version }}-${{ runner.os }}
         path: |
           neo4j-community-*-unix.tar.gz
-          OpenJDK*.tar.gz
 
     - name: Resolve Neo4j version
       run: |
@@ -94,22 +93,43 @@ runs:
           echo "Resolved Neo4j '$ALIAS' to Neo4j '$NEO4J'."
         fi
         echo "neo4j-version=$NEO4J" >> "$GITHUB_OUTPUT"
+
+        NEO4J_MAJOR_VERSION=$( echo "$NEO4J" | perl -pe 's/\D.*//' )
+        case "$NEO4J_MAJOR_VERSION" in
+          [123]    ) JAVA=8   ;;
+          4        ) JAVA=11  ;;
+          5        ) JAVA=17  ;;
+          *        ) JAVA=21  ;;
+        esac
+        echo "java-version=$JAVA" >> "$GITHUB_OUTPUT"
       shell: bash
       id: aliases
 
-    - name: Install Neo4j 5
+    - name: Install Java
+      uses: actions/setup-java@v4
+      with:
+        distribution: temurin
+        java-version: ${{ steps.aliases.outputs.java-version }}
+
+    - name: Install Neo4j
+      run: |
+        NEO4J="${{ steps.aliases.outputs.neo4j-version }}"
+        if [ ! -e "neo4j-community-$NEO4J-unix.tar.gz" ]
+        then
+          echo "Cache miss, downloading Neo4j $NEO4J"
+          NEO4J_DISTS="${{ inputs.neo4j-dist-url }}"
+          curl -sLO $NEO4J_DISTS/neo4j-community-$NEO4J-unix.tar.gz
+        fi
+        tar -xzf neo4j-community-$NEO4J-unix.tar.gz
+
+        eval "${JAVA_HOME:-/usr}/bin/java -version"
+        echo "$JAVA_HOME" | tee neo4j-javahome
+      shell: bash
+
+    - name: Start Neo4j 5
       if: ${{ startsWith( steps.aliases.outputs.neo4j-version , '5.') }}
       run: |
-        NEO4J_DISTS="${{ inputs.neo4j-dist-url }}"
         NEO4J="${{ steps.aliases.outputs.neo4j-version }}"
-        [ -e "neo4j-community-$NEO4J-unix.tar.gz" ] && CACHE_HIT=1
-        [ -n "$CACHE_HIT" ] || curl -sLO https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.9%2B9/OpenJDK17U-jre_x64_linux_hotspot_17.0.9_9.tar.gz
-        tar -xzf OpenJDK17U-jre_x64_linux_hotspot_17.0.9_9.tar.gz
-        export JAVA_HOME="$(pwd)/jdk-17.0.9+9-jre"
-        echo "$JAVA_HOME" > neo4j-javahome
-        eval "${JAVA_HOME:-/usr}/bin/java -version"
-        [ -n "$CACHE_HIT" ] || curl -sLO $NEO4J_DISTS/neo4j-community-$NEO4J-unix.tar.gz
-        tar -xzf neo4j-community-$NEO4J-unix.tar.gz
         neo4j-community-$NEO4J/bin/neo4j-admin dbms set-initial-password "${{ inputs.password }}" || echo "Password change using neo4j-admin failed."
         neo4j-community-$NEO4J/bin/neo4j start
         perl -E "print'Waiting for server to be ready ...';for(0..60){last if 0+\`grep Started neo4j-community-$NEO4J/logs/neo4j.log > /dev/null 2>&1 && echo 1 || echo 0\`;print'.';sleep 1}say' OK.'"
@@ -117,19 +137,10 @@ runs:
         neo4j-community-$NEO4J/bin/neo4j status
       shell: bash
 
-    - name: Install Neo4j 4
-      if: ${{ startsWith( steps.aliases.outputs.neo4j-version , '4.') }}
+    - name: Start Neo4j 3/4
+      if: ${{ startsWith( steps.aliases.outputs.neo4j-version , '3.') || startsWith( steps.aliases.outputs.neo4j-version , '4.') }}
       run: |
-        NEO4J_DISTS="${{ inputs.neo4j-dist-url }}"
         NEO4J="${{ steps.aliases.outputs.neo4j-version }}"
-        [ -e "neo4j-community-$NEO4J-unix.tar.gz" ] && CACHE_HIT=1
-        [ -n "$CACHE_HIT" ] || curl -sLO https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jre_x64_linux_hotspot_11.0.22_7.tar.gz
-        tar -xzf OpenJDK11U-jre_x64_linux_hotspot_11.0.22_7.tar.gz
-        export JAVA_HOME="$(pwd)/jdk-11.0.22+7-jre"
-        echo "$JAVA_HOME" > neo4j-javahome
-        eval "${JAVA_HOME:-/usr}/bin/java -version"
-        [ -n "$CACHE_HIT" ] || curl -sLO $NEO4J_DISTS/neo4j-community-$NEO4J-unix.tar.gz
-        tar -xzf neo4j-community-$NEO4J-unix.tar.gz
         neo4j-community-$NEO4J/bin/neo4j-admin set-initial-password "${{ inputs.password }}" || echo "Password change using neo4j-admin failed."
         neo4j-community-$NEO4J/bin/neo4j start
         perl -E "print'Waiting for server to be ready ...';for(0..60){last if 0+\`grep Started neo4j-community-$NEO4J/logs/neo4j.log > /dev/null 2>&1 && echo 1 || echo 0\`;print'.';sleep 1}say' OK.'"
@@ -137,31 +148,14 @@ runs:
         neo4j-community-$NEO4J/bin/neo4j status
       shell: bash
 
-    - name: Install Neo4j 2/3
-      if: ${{ startsWith( steps.aliases.outputs.neo4j-version , '3.') || startsWith( steps.aliases.outputs.neo4j-version , '2.') || startsWith( steps.aliases.outputs.neo4j-version , '1.') }}
+    - name: Start Neo4j 1/2
+      if: ${{ startsWith( steps.aliases.outputs.neo4j-version , '1.') || startsWith( steps.aliases.outputs.neo4j-version , '2.') }}
       run: |
-        NEO4J_DISTS="${{ inputs.neo4j-dist-url }}"
         NEO4J="${{ steps.aliases.outputs.neo4j-version }}"
-        [ -e "neo4j-community-$NEO4J-unix.tar.gz" ] && CACHE_HIT=1
-        [ -n "$CACHE_HIT" ] || curl -sLO https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u392-b08/OpenJDK8U-jre_x64_linux_hotspot_8u392b08.tar.gz
-        tar -xzf OpenJDK8U-jre_x64_linux_hotspot_8u392b08.tar.gz
-        export JAVA_HOME="$(pwd)/jdk8u392-b08-jre"
-        echo "$JAVA_HOME" > neo4j-javahome
-        eval "${JAVA_HOME:-/usr}/bin/java -version"
-        [ -n "$CACHE_HIT" ] || curl -sLO $NEO4J_DISTS/neo4j-community-$NEO4J-unix.tar.gz
-        tar -xzf neo4j-community-$NEO4J-unix.tar.gz
-        neo4j-community-$NEO4J/bin/neo4j-admin set-initial-password "${{ inputs.password }}" || echo "Password change using neo4j-admin failed. (This is expected on Neo4j 2.)"
-        NEO4J_LOG=logs/neo4j.log
-        if perl -e 'exit $ARGV[0] !~ /^[12]\./' "$NEO4J"
-        then
-          neo4j-community-$NEO4J/bin/neo4j start-no-wait
-          NEO4J_LOG=data/log/console.log
-        else
-          neo4j-community-$NEO4J/bin/neo4j start
-        fi
-        perl -E "print'Waiting for server to be ready ...';for(0..60){last if 0+\`grep 'Started\\\|interface ready' neo4j-community-$NEO4J/$NEO4J_LOG > /dev/null 2>&1 && echo 1 || echo 0\`;print'.';sleep 1}say' OK.'"
+        neo4j-community-$NEO4J/bin/neo4j start-no-wait
+        perl -E "print'Waiting for server to be ready ...';for(0..60){last if 0+\`grep 'Started\\\|interface ready' neo4j-community-$NEO4J/data/log/console.log > /dev/null 2>&1 && echo 1 || echo 0\`;print'.';sleep 1}say' OK.'"
         sleep 1
-        curl -u neo4j:neo4j -fid "{\"password\":\"${{ inputs.password }}\"}" -H "Content-Type:application/json" -s http://localhost:7474/user/neo4j/password || echo "Password change using cURL failed. (This is expected on Neo4j 3.)"
-        cat neo4j-community-$NEO4J/$NEO4J_LOG
+        curl -u neo4j:neo4j -fid "{\"password\":\"${{ inputs.password }}\"}" -H "Content-Type:application/json" -s http://localhost:7474/user/neo4j/password || echo "Password change using cURL failed. (This is expected on Neo4j 1.)"
+        cat neo4j-community-$NEO4J/data/log/console.log
         neo4j-community-$NEO4J/bin/neo4j status
       shell: bash
